config/routes.rb
Rails.application.routes.draw do
  resources :stuffings
  # EXAMPLE HTML ROUTE
  # get "/photos" => "photos#index"

  # EXAMPLE JSON ROUTE WITH API NAMESPACE
  # namespace :api do
  #   get "/photos" => "photos#index"
  # end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stuffing.rb
class Stuffing < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :null_session
end

app/controllers/stuffings_controller.rb
class StuffingsController < ApplicationController
  before_action :set_stuffing, only: [:show, :edit, :update, :destroy]

  # GET /stuffings
  # GET /stuffings.json
  def index
    @stuffings = Stuffing.all
  end

  # GET /stuffings/1
  # GET /stuffings/1.json
  def show
  end

  # GET /stuffings/new
  def new
    @stuffing = Stuffing.new
  end

  # GET /stuffings/1/edit
  def edit
  end

  # POST /stuffings
  # POST /stuffings.json
  def create
    @stuffing = Stuffing.new(stuffing_params)

    respond_to do |format|
      if @stuffing.save
        format.html { redirect_to @stuffing, notice: 'Stuffing was successfully created.' }
        format.json { render :show, status: :created, location: @stuffing }
      else
        format.html { render :new }
        format.json { render json: @stuffing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stuffings/1
  # PATCH/PUT /stuffings/1.json
  def update
    respond_to do |format|
      if @stuffing.update(stuffing_params)
        format.html { redirect_to @stuffing, notice: 'Stuffing was successfully updated.' }
        format.json { render :show, status: :ok, location: @stuffing }
      else
        format.html { render :edit }
        format.json { render json: @stuffing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stuffings/1
  # DELETE /stuffings/1.json
  def destroy
    @stuffing.destroy
    respond_to do |format|
      format.html { redirect_to stuffings_url, notice: 'Stuffing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stuffing
      @stuffing = Stuffing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stuffing_params
      params.require(:stuffing).permit(:color, :weight, :description, :flavor)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TurkeyApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/stuffings/_form.html.erb
<%= form_with(model: stuffing, local: true) do |form| %>
  <% if stuffing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stuffing.errors.count, "error") %> prohibited this stuffing from being saved:</h2>

      <ul>
        <% stuffing.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :color %>
    <%= form.text_field :color %>
  </div>

  <div class="field">
    <%= form.label :weight %>
    <%= form.number_field :weight %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :flavor %>
    <%= form.text_field :flavor %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stuffings/edit.html.erb
<h1>Editing Stuffing</h1>

<%= render 'form', stuffing: @stuffing %>

<%= link_to 'Show', @stuffing %> |
<%= link_to 'Back', stuffings_path %>

app/views/stuffings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stuffings</h1>

<table>
  <thead>
    <tr>
      <th>Color</th>
      <th>Weight</th>
      <th>Description</th>
      <th>Flavor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stuffings.each do |stuffing| %>
      <tr>
        <td><%= stuffing.color %></td>
        <td><%= stuffing.weight %></td>
        <td><%= stuffing.description %></td>
        <td><%= stuffing.flavor %></td>
        <td><%= link_to 'Show', stuffing %></td>
        <td><%= link_to 'Edit', edit_stuffing_path(stuffing) %></td>
        <td><%= link_to 'Destroy', stuffing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stuffing', new_stuffing_path %>

app/views/stuffings/new.html.erb
<h1>New Stuffing</h1>

<%= render 'form', stuffing: @stuffing %>

<%= link_to 'Back', stuffings_path %>

app/views/stuffings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Color:</strong>
  <%= @stuffing.color %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @stuffing.weight %>
</p>

<p>
  <strong>Description:</strong>
  <%= @stuffing.description %>
</p>

<p>
  <strong>Flavor:</strong>
  <%= @stuffing.flavor %>
</p>

<%= link_to 'Edit', edit_stuffing_path(@stuffing) %> |
<%= link_to 'Back', stuffings_path %>